# Generated by Django 2.2.2 on 2019-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
